name: Check GitHub System Time

on:
  schedule:
    # 19:55 TSI (16:55 UTC)
    - cron: '55 16 * * *'
  workflow_dispatch:

jobs:
  check-time:
    runs-on: ubuntu-latest
    steps:
      - name: Print Current Time
        run: |
          echo "GitHub System Time (UTC): $(date)"
          echo "GitHub System Time (Formatted): $(date +'%H:%M')"
